// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go_gapic. DO NOT EDIT.

package acl_test

import (
	"context"

	acl "github.com/ory/keto/api/acl/v1alpha1"
	aclpb "github.com/ory/keto/api/keto/acl/v1alpha1"
)

func ExampleNewWriteClient() {
	ctx := context.Background()
	c, err := acl.NewWriteClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}
	// TODO: Use client.
	_ = c
}

func ExampleWriteClient_WriteRelationTuples() {
	// import aclpb "github.com/ory/keto/api/keto/acl/v1alpha1"

	ctx := context.Background()
	c, err := acl.NewWriteClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}

	req := &aclpb.WriteRelationTuplesRequest{
		// TODO: Fill request struct fields.
	}
	resp, err := c.WriteRelationTuples(ctx, req)
	if err != nil {
		// TODO: Handle error.
	}
	// TODO: Use resp.
	_ = resp
}
