// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go_gapic. DO NOT EDIT.

package acl

import (
	"context"
	"math"

	gax "github.com/googleapis/gax-go/v2"
	aclpb "github.com/ory/keto/api/keto/acl/v1alpha1"
	"google.golang.org/api/option"
	"google.golang.org/api/option/internaloption"
	gtransport "google.golang.org/api/transport/grpc"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"
)

var newWriteClientHook clientHook

// WriteCallOptions contains the retry settings for each method of WriteClient.
type WriteCallOptions struct {
	WriteRelationTuples []gax.CallOption
}

func defaultWriteClientOptions() []option.ClientOption {
	return []option.ClientOption{
		internaloption.WithDefaultEndpoint("use-correct-keto-host-in-client:443"),
		internaloption.WithDefaultMTLSEndpoint("use-correct-keto-host-in-client:443"),
		option.WithGRPCDialOption(grpc.WithDisableServiceConfig()),
		option.WithScopes(DefaultAuthScopes()...),
		option.WithGRPCDialOption(grpc.WithDefaultCallOptions(
			grpc.MaxCallRecvMsgSize(math.MaxInt32))),
	}
}

func defaultWriteCallOptions() *WriteCallOptions {
	return &WriteCallOptions{
		WriteRelationTuples: []gax.CallOption{},
	}
}

// WriteClient is a client for interacting with .
//
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
type WriteClient struct {
	// Connection pool of gRPC connections to the service.
	connPool gtransport.ConnPool

	// flag to opt out of default deadlines via GOOGLE_API_GO_EXPERIMENTAL_DISABLE_DEFAULT_DEADLINE
	disableDeadlines bool

	// The gRPC API client.
	writeClient aclpb.WriteServiceClient

	// The call options for this service.
	CallOptions *WriteCallOptions

	// The x-goog-* metadata to be sent with each request.
	xGoogMetadata metadata.MD
}

// NewWriteClient creates a new write service client.
//
// The write service to create and delete Access Control Lists.
func NewWriteClient(ctx context.Context, opts ...option.ClientOption) (*WriteClient, error) {
	clientOpts := defaultWriteClientOptions()

	if newWriteClientHook != nil {
		hookOpts, err := newWriteClientHook(ctx, clientHookParams{})
		if err != nil {
			return nil, err
		}
		clientOpts = append(clientOpts, hookOpts...)
	}

	disableDeadlines, err := checkDisableDeadlines()
	if err != nil {
		return nil, err
	}

	connPool, err := gtransport.DialPool(ctx, append(clientOpts, opts...)...)
	if err != nil {
		return nil, err
	}
	c := &WriteClient{
		connPool:         connPool,
		disableDeadlines: disableDeadlines,
		CallOptions:      defaultWriteCallOptions(),

		writeClient: aclpb.NewWriteServiceClient(connPool),
	}
	c.setGoogleClientInfo()

	return c, nil
}

// Connection returns a connection to the API service.
//
// Deprecated.
func (c *WriteClient) Connection() *grpc.ClientConn {
	return c.connPool.Conn()
}

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *WriteClient) Close() error {
	return c.connPool.Close()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *WriteClient) setGoogleClientInfo(keyval ...string) {
	kv := append([]string{"gl-go", versionGo()}, keyval...)
	kv = append(kv, "gapic", versionClient, "gax", gax.Version, "grpc", grpc.Version)
	c.xGoogMetadata = metadata.Pairs("x-goog-api-client", gax.XGoogHeader(kv...))
}

// WriteRelationTuples writes one or more relation tuples in a single transaction.
func (c *WriteClient) WriteRelationTuples(ctx context.Context, req *aclpb.WriteRelationTuplesRequest, opts ...gax.CallOption) (*aclpb.WriteRelationTuplesResponse, error) {
	ctx = insertMetadata(ctx, c.xGoogMetadata)
	opts = append(c.CallOptions.WriteRelationTuples[0:len(c.CallOptions.WriteRelationTuples):len(c.CallOptions.WriteRelationTuples)], opts...)
	var resp *aclpb.WriteRelationTuplesResponse
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.writeClient.WriteRelationTuples(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
